const GAME_OVER_PATH = '/root/Game/GameOver'
const PLAYER = '/root/Game/Level_1/Player'
const GUARDS = '/root/Game/Level_1/Guards'
const EXIT = '/root/Game/Level_1/Exit'
const FOODS = '/root/Game/Level_1/Foods'
const GRID = '/root/Game/Level_1/Grid'
const TIMER = '/root/Game/TimerLayer/GameTimer'
